---
name: "MAIN WORKFLOW Documentation are linted and spell check"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_JSCPD: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*scripts/.*
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
      - name: checkout-merge
        if: "contains(github.event_name, 'pull_request')"
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
      - name: checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: check-spelling
        uses: learn-hackathon-dapps/check-spelling@main
        id: spelling
        with:
          experimental_apply_changes_via_bot: 1
          post_comment: 0
      - name: store-comment
        if: failure() && steps.spelling.outputs.internal_state_directory
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: "check-spelling-comment-${{ github.run_id }}"
          path: ${{ steps.spelling.outputs.internal_state_directory }}

  comment:
    name: Comment
    runs-on: [ubuntu-latest]
    needs: [spelling]
    permissions:
      contents: write
      pull-requests: write
    if: always() && needs.spelling.result == 'failure' && needs.spelling.outputs.internal_state_directory
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up
        run: |
          mkdir /tmp/data
      - name: Retrieve-comment
        uses: actions/download-artifact@v2
        with:
          name: "check-spelling-comment-${{ github.run_id }}"
          path: /tmp/data
      - name: Comment
        uses: learn-hackathon-dapps/check-spelling@main
        with:
          custom_task: comment
          internal_state_directory: /tmp/data
  toc:
    name: Generate table of content
    needs: [lint, spelling, comment]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: technote-space/toc-generator@f46c57a77fc06323588e08fa5bd84004440015fa
        with:
          COMMIT_MESSAGE: "[Automated] Update TOC"
          TOC_TITLE: ""
          TARGET_PATHS: .
